### ISSUE TITLE
Incorrect line number when running js script via run_js_test

### ISSUE THREAD

**Issue by ochameau** [luser/luciddream#6]
No matter what, it always reports line 851 when there is an exception in a JS test script
```
TEST-UNEXPECTED-ERROR | test_sample.py TestSample.test_sample | JavascriptException: JavascriptException: SyntaxError: unterminated string literal
stacktrace:
	execute_async_script @test_chrome.js
	inline javascript, line 851
	src: "undefined"



Traceback (most recent call last):
  File "/home/alex/luciddream/ve/local/lib/python2.7/site-packages/marionette_client-0.8.5-py2.7.egg/marionette/marionette_test.py", line 267, in run
    testMethod()
  File "/home/alex/luciddream/alex-tests/test_sample.py", line 41, in test_sample
    self.run_js_test("test_chrome.js", self.browser)
  File "/home/alex/luciddream/luciddream/__init__.py", line 65, in run_js_test
    filename=os.path.basename(script))
  File "/home/alex/luciddream/ve/local/lib/python2.7/site-packages/marionette_client-0.8.5-py2.7.egg/marionette/marionette.py", line 1158, in execute_js_script
    line=None)
  File "/home/alex/luciddream/ve/local/lib/python2.7/site-packages/marionette_client-0.8.5-py2.7.egg/marionette/decorators.py", line 36, in _
    return func(*args, **kwargs)
  File "/home/alex/luciddream/ve/local/lib/python2.7/site-packages/marionette_client-0.8.5-py2.7.egg/marionette/marionette.py", line 630, in _send_message
    self._handle_error(response)
  File "/home/alex/luciddream/ve/local/lib/python2.7/site-packages/marionette_client-0.8.5-py2.7.egg/marionette/marionette.py", line 678, in _handle_error
    raise errors.JavascriptException(message=message, status=status, stacktrace=stacktrace)
```

It would really help debugging failures if we display the right line number!
Having said that, I'm not able to reproduce it with the simple example-test,
but it easily reproduces with https://github.com/ochameau/luciddream/commit/303836c58516d637ea67adbe71fff1e01a3b8654
Just remove a `"` from a string and you will get a report for line 851...

**Comment by luser** [comment]
So here's where that error message gets generated on the server (inside the browser) side:
https://hg.mozilla.org/mozilla-central/annotate/2cb22c058add/testing/marionette/marionette-listener.js#l572

You can see up above that where it prepends a whole bunch of extra JS to the script you actually pass in:
https://hg.mozilla.org/mozilla-central/annotate/2cb22c058add/testing/marionette/marionette-listener.js#l572

This is where it injects the scripts that give you ok()/finish() etc. This is definitely a crummy error message. File a Marionette bug to see if there's some way we can improve this?
